// Generated by gencpp from file marker_msg/status.msg
// DO NOT EDIT!


#ifndef MARKER_MSG_MESSAGE_STATUS_H
#define MARKER_MSG_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marker_msg
{
template <class ContainerAllocator>
struct status_
{
  typedef status_<ContainerAllocator> Type;

  status_()
    : status()
    , x(0.0)
    , y(0.0)
    , w(0.0)  {
    }
  status_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , x(0.0)
    , y(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::marker_msg::status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marker_msg::status_<ContainerAllocator> const> ConstPtr;

}; // struct status_

typedef ::marker_msg::status_<std::allocator<void> > status;

typedef boost::shared_ptr< ::marker_msg::status > statusPtr;
typedef boost::shared_ptr< ::marker_msg::status const> statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marker_msg::status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marker_msg::status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace marker_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'marker_msg': ['/home/workspace/catkin_ws/src/Robotics_Project5/marker_msg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::marker_msg::status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marker_msg::status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_msg::status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marker_msg::status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_msg::status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marker_msg::status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marker_msg::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e04b4c545b887ef56c6688a5b36a345";
  }

  static const char* value(const ::marker_msg::status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e04b4c545b887efULL;
  static const uint64_t static_value2 = 0x56c6688a5b36a345ULL;
};

template<class ContainerAllocator>
struct DataType< ::marker_msg::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marker_msg/status";
  }

  static const char* value(const ::marker_msg::status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marker_msg::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n\
float64 x\n\
float64 y\n\
float64 w\n\
";
  }

  static const char* value(const ::marker_msg::status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marker_msg::status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marker_msg::status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marker_msg::status_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARKER_MSG_MESSAGE_STATUS_H
